image: python:latest

stages:
  - build
  - report

python-version-test:
  stage: build
  script:
    - pip install -r requirements.txt
    - python NceGitLab.py

generate-reports:
  stage: report
  script:
    - pip install -r requirements.txt
    - python NceGitLab.py --report all
    - zip -r reports.zip reports/
  artifacts:
    name: "reports-${CI_COMMIT_SHORT_SHA}"
    paths:
      - reports.zip
    expire_in: 30 days
  variables:
    ACCESS_TOKEN: $ACCESS_TOKEN
    GROUP_NAME: $GROUP_NAME
  when: manual
